"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FIND_NOREDACT = exports.FIND_REMOVED = exports.FIND_FIRST = exports.MobilettoNoopFunc = exports.MobilettoMatchAll = void 0;
const MobilettoMatchAll = () => true;
exports.MobilettoMatchAll = MobilettoMatchAll;
const MobilettoNoopFunc = (thing) => Promise.resolve(null);
exports.MobilettoNoopFunc = MobilettoNoopFunc;
exports.FIND_FIRST = { first: true };
exports.FIND_REMOVED = { removed: true };
exports.FIND_NOREDACT = { noRedact: true };
